# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7716e19185efb4a400fdbeb3344a1f9edcbc81fd40d5b4d3f9b80598d05d32ab64889c0cc9da6a70b60477f42acc9d1bb085a0ae5e42eab4064806a3ee778488

test:
  secret_key_base: 21c650d704c57e2c3b581080beeef303b1d99bda5cdd339a1c712509e433fe991c72c6a9e1b28df65d1d9a6e8f0ab6b6301adaaa76c27612c7997c50dad06cc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
